/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

DROP TABLE IF EXISTS `customer`;

CREATE TABLE `customer` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`first_name` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`last_name` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`email_address` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_bin',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `ix_customer_email` (`email_address`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB;


DROP TABLE IF EXISTS `address`;

CREATE TABLE `address` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`customer_id` BIGINT(20) NULL DEFAULT NULL,	
	`street` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`city` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`country` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_bin',	
	PRIMARY KEY (`id`),
	INDEX `FK_ADDRESS_CUSTOMER_ID` (`customer_id`),
	CONSTRAINT `FK_CUSTOMER_CUSTOMER_ID` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB;

/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
